target 'CocoapodsInstallation' do
  use_frameworks!
  platform :ios, '11.0'

  pod 'PurchasesCore', :git => 'git@github.com:RevenueCat/purchases-core.git', :branch => 'rust'
  pod 'RevenueCat', path: '../../../'
  
  target 'CocoapodsInstallationTests' do
    inherit! :search_paths
  end

end

target 'CocoapodsRevenueCatUIInstallation' do
  use_frameworks!
  platform :ios, '11.0'

  pod 'PurchasesCore', :git => 'git@github.com:RevenueCat/purchases-core.git', :branch => 'rust'
  pod 'RevenueCat', path: '../../../'
  pod 'RevenueCatUI', path: '../../../'
  
  target 'CocoapodsRevenueCatUIInstallationTests' do
    inherit! :search_paths
  end

end
