excluded:
  - Carthage
  - Pods
  - PurchasesTests
  - PurchasesCoreSwiftTests
  - Examples
  - IntegrationTests
  - StoreKitTests
  - vendor
  - scan_derived_data
  - .build

disabled_rules:
  - trailing_comma
  - blanket_disable_command

identifier_name: 
  max_length: 
    warning: 60 
    error: 80
