excluded:
  - Carthage
  - Examples
  - Tests/InstallationTests
  - Tests/TestingApps
  - vendor
  - scan_derived_data
  - .git
  - .build

opt_in_rules:
  - sorted_imports
  - missing_docs
  - convenience_type
  - multiline_parameters
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call

custom_rules:
  xctestcase_superclass:
    included: ".*\\.swift"
    excluded: Tests/BackendIntegrationTests
    regex: "\\: XCTestCase \\{"
    name: "XCTestCase Superclass"
    message: "Test classes must inherit `TestCase` instead."

identifier_name:
  max_length: 
    warning: 60 
    error: 80

missing_docs:
  excludes_inherited_types: false
