excluded:
  - Carthage
  - Pods
  - PurchasesTests
  - PurchasesCoreSwiftTests
  - Examples
  - IntegrationTests
  - StoreKitTests
  - PublicSDKAPITester
  - vendor
  - scan_derived_data
disabled_rules:
  - trailing_comma
  - todo
  - cyclomatic_complexity
  - function_body_length
  - identifier_name
  - line_length
opt_in_rules:
  - sorted_imports
  # TODO: enable this rule after the swift migration is finished.
  # - missing_docs
identifier_name:
  max_length: 
    warning: 60 
    error: 80
