excluded:
  - Carthage
  - Pods
  - PurchasesTests
  - PurchasesCoreSwiftTests
  - Examples
  - IntegrationTests
  - StoreKitTests
  - PublicSDKAPITester
disabled_rules:
  - trailing_comma
  - todo
  - cyclomatic_complexity
  - function_body_length
identifier_name: 
  max_length: 
    warning: 60 
    error: 80