excluded:
  - Carthage
  - Pods
  - PurchasesTests
  - Examples
  - IntegrationTests
  - BackendIntegrationTests
  - PublicSDKAPITester
  - vendor
  - scan_derived_data

opt_in_rules:
  - sorted_imports
  - missing_docs
  - convenience_type
  - multiline_parameters
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call

identifier_name:
  max_length: 
    warning: 60 
    error: 80

