//
//   Copyright RevenueCat Inc. All Rights Reserved.
//
//   Licensed under the MIT License (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       https://opensource.org/licenses/MIT
//
//   CustomerCenterLocalization.swift
//
// swiftlint:disable missing_docs file_length type_body_length
import RevenueCat

extension CustomerCenterConfigData {

  public struct Localization : Equatable {

    let locale: String
    let localizedStrings: [String: String]
    public subscript(_ key: CommonLocalizedString) -> String {
      return localizedStrings[key.rawValue] ?? key.defaultValue}

    public init(locale: String, localizedStrings: [String: String]) {
      self.locale = locale
      self.localizedStrings = localizedStrings}

    public enum CommonLocalizedString : String, Equatable {

      case active = "active"
      case amazonStore = "amazon_store"
      case amazonSubscriptionManage = "amazon_subscription_manage"
      case appStore = "app_store"
      case appleSubscriptionManage = "apple_subscription_manage"
      case billingCycle = "billing_cycle"
      case billingIssueDetectedAt = "billing_issue_detected_at"
      case cancel = "cancel"
      case cancelSurveyTitle = "cancel_survey_title"
      case checkPastPurchases = "check_past_purchases"
      case contactSupport = "contact_support"
      case copyTitle = "copy_title"
      case currentPrice = "current_price"
      case debug = "debug"
      case defaultBody = "default_body"
      case defaultSubject = "default_subject"
      case discountedRecurringThenPrice = "discounted_recurring_then_price"
      case dismiss = "dismiss"
      case done = "done"
      case expired = "expired"
      case expires = "expires"
      case expiresOnDateWithoutChanges = "expires_on_date_without_changes"
      case externalStore = "external_store"
      case free = "free"
      case freeTrialDiscountedThenPrice = "free_trial_discounted_then_price"
      case freeTrialSinglePaymentThenPrice = "free_trial_single_payment_then_price"
      case freeTrialThenPrice = "free_trial_then_price"
      case freeTrialUntilDate = "free_trial_until_date"
      case goingToCheckPurchases = "going_to_check_purchases"
      case googlePlayStore = "google_play_store"
      case googleSubscriptionManage = "google_subscription_manage"
      case gracePeriodExpiresAt = "grace_period_expires_at"
      case inactive = "inactive"
      case introductoryPrice = "introductory_price"
      case macAppStore = "mac_app_store"
      case manageSubscription = "manage_subscription"
      case never = "never"
      case nextBillingDate = "next_billing_date"
      case nextRenewal = "next_renewal"
      case no = "no"
      case noActiveCheckPurchases = "no_active_check_purchases"
      case noSubscriptionsFound = "no_subscriptions_found"
      case noThanks = "no_thanks"
      case originalDownloadDate = "original_download_date"
      case paidPrice = "paid_price"
      case pathCancel = "path_cancel"
      case pathChange = "path_change"
      case pathMissingPurchase = "path_missing_purchase"
      case pathRefund = "path_refund"
      case periodType = "period_type"
      case platformMismatch = "platform_mismatch"
      case pleaseContactSupport = "please_contact_support"
      case priceAfterwards = "price_afterwards"
      case pricePaid = "price_paid"
      case productId = "product_id"
      case productName = "product_name"
      case promoOfferSubtitle = "promo_offer_subtitle"
      case promoOfferTitle = "promo_offer_title"
      case promotional = "promotional"
      case purchaseInfoExpiredOnDate = "purchase_info_expired_on_date"
      case purchaseInfoExpiresOnDate = "purchase_info_expires_on_date"
      case purchaseInfoPurchasedOnDate = "purchase_info_purchased_on_date"
      case purchaseInfoRenewsOnDate = "purchase_info_renews_on_date"
      case purchasesNotFound = "purchases_not_found"
      case purchasesNotRecovered = "purchases_not_recovered"
      case purchasesRecovered = "purchases_recovered"
      case purchasesRecoveredExplanation = "purchases_recovered_explanation"
      case purchasesRestoring = "purchases_restoring"
      case refundCanceled = "refund_canceled"
      case refundErrorGeneric = "refund_error_generic"
      case refundGranted = "refund_granted"
      case refundStatus = "refund_status"
      case refundedAt = "refunded_at"
      case renewsOnDate = "renews_on_date"
      case renewsOnDateForPrice = "renews_on_date_for_price"
      case restorePurchases = "restore_purchases"
      case sandbox = "sandbox"
      case screenManagementSeeAllPurchases = "screen_management_see_all_purchases"
      case screenManagementTitle = "screen_management_title"
      case screenNoActiveSubtitle = "screen_no_active_subtitle"
      case screenNoActiveTitle = "screen_no_active_title"
      case screenPurchaseHistoryAccountDetailsTitle = "screen_purchase_history_account_details_title"
      case screenPurchaseHistoryActiveSubscriptionsTitle = "screen_purchase_history_active_subscriptions_title"
      case screenPurchaseHistoryExpiredSubscriptionsTitle = "screen_purchase_history_expired_subscriptions_title"
      case screenPurchaseHistoryOriginalPurchaseDate = "screen_purchase_history_original_purchase_date"
      case screenPurchaseHistoryOthersTitle = "screen_purchase_history_others_title"
      case screenPurchaseHistoryTitle = "screen_purchase_history_title"
      case screenPurchaseHistoryUserId = "screen_purchase_history_user_id"
      case sharedThroughFamilyMember = "shared_through_family_member"
      case singlePaymentThenPrice = "single_payment_then_price"
      case status = "status"
      case store = "store"
      case stripe = "stripe"
      case subEarliestExpiration = "sub_earliest_expiration"
      case subEarliestRenewal = "sub_earliest_renewal"
      case subExpired = "sub_expired"
      case surveyMistake = "survey_mistake"
      case surveyTooExpensive = "survey_too_expensive"
      case surveyUsage = "survey_usage"
      case transactionId = "transaction_id"
      case trialPeriod = "trial_period"
      case tryCheckRestore = "try_check_restore"
      case unknown = "unknown"
      case unknownStore = "unknown_store"
      case unsubscribedAt = "unsubscribed_at"
      case updateWarningDescription = "update_warning_description"
      case updateWarningIgnore = "update_warning_ignore"
      case updateWarningTitle = "update_warning_title"
      case updateWarningUpdate = "update_warning_update"
      case webStore = "web_store"
      case webSubscriptionManage = "web_subscription_manage"
      case yes = "yes"
      case youHaveLifetime = "you_have_lifetime"
      case youHavePromo = "you_have_promo"
      case youMayHaveDuplicatedSubscriptionsSubtitle = "you_may_have_duplicated_subscriptions_subtitle"
      case youMayHaveDuplicatedSubscriptionsTitle = "you_may_have_duplicated_subscriptions_title"

      public var defaultValue: String {
        switch self {
        case .active: return "Active"
        case .amazonStore: return "Amazon Store"
        case .amazonSubscriptionManage: return "You have an active subscription from the Amazon Appstore. You can manage your subscription in the Amazon Appstore app."
        case .appStore: return "App Store"
        case .appleSubscriptionManage: return "You can manage your subscription by using the App Store app on an Apple device."
        case .billingCycle: return "Billing cycle"
        case .billingIssueDetectedAt: return "Billing Issue Detected At"
        case .cancel: return "Cancel"
        case .cancelSurveyTitle: return "Why are you cancelling?"
        case .checkPastPurchases: return "Check past purchases"
        case .contactSupport: return "Contact support"
        case .copyTitle: return "Copy"
        case .currentPrice: return "Price"
        case .debug: return "Debug"
        case .defaultBody: return "Please describe your issue or question."
        case .defaultSubject: return "Support Request"
        case .discountedRecurringThenPrice: return "{{ sub_offer_price }} during {{ sub_offer_duration }}, then {{ price }}"
        case .dismiss: return "Dismiss"
        case .done: return "Done"
        case .expired: return "Expired"
        case .expires: return "Expires"
        case .expiresOnDateWithoutChanges: return "Expires on {{ date }} without further charges."
        case .externalStore: return "External"
        case .free: return "Free"
        case .freeTrialDiscountedThenPrice: return "{{ sub_offer_duration }} for free, then {{ sub_offer_price_2 }} during {{ sub_offer_duration_2 }}, and {{ price }} thereafter"
        case .freeTrialSinglePaymentThenPrice: return "{{ sub_offer_duration }} for free, then {{ sub_offer_duration_2 }} for {{ sub_offer_price_2 }}, and {{ price }} thereafter"
        case .freeTrialThenPrice: return "{{ sub_offer_duration }} free, then {{ price }}"
        case .freeTrialUntilDate: return "Free trial until {{ date }}"
        case .goingToCheckPurchases: return "Let’s take a look! We’re going to check your account for missing purchases."
        case .googlePlayStore: return "Google Play Store"
        case .googleSubscriptionManage: return "You have an active subscription from the Google Play Store"
        case .gracePeriodExpiresAt: return "Grace Period Expires At"
        case .inactive: return "Inactive"
        case .introductoryPrice: return "Introductory Price"
        case .macAppStore: return "Mac App Store"
        case .manageSubscription: return "Manage your subscription"
        case .never: return "Never"
        case .nextBillingDate: return "Next billing date"
        case .nextRenewal: return "Next Renewal"
        case .no: return "No"
        case .noActiveCheckPurchases: return "Restore past purchases"
        case .noSubscriptionsFound: return "No Subscriptions found"
        case .noThanks: return "No, thanks"
        case .originalDownloadDate: return "Original Download Date"
        case .paidPrice: return "Paid price"
        case .pathCancel: return "Cancel subscription"
        case .pathChange: return "Change plans"
        case .pathMissingPurchase: return "Restore past purchases"
        case .pathRefund: return "Request a refund"
        case .periodType: return "Period Type"
        case .platformMismatch: return "Platform mismatch"
        case .pleaseContactSupport: return "Please contact support to manage your subscription."
        case .priceAfterwards: return "{{ price }} afterwards."
        case .pricePaid: return "Paid {{ price }}"
        case .productId: return "Product ID"
        case .productName: return "Product name"
        case .promoOfferSubtitle: return "Before you go, here’s a one-time offer to continue at a discount."
        case .promoOfferTitle: return "Wait!"
        case .promotional: return "Promotional"
        case .purchaseInfoExpiredOnDate: return "Expired on {{ date }}"
        case .purchaseInfoExpiresOnDate: return "Expires on {{ date }}"
        case .purchaseInfoPurchasedOnDate: return "Purchased on {{ date }}"
        case .purchaseInfoRenewsOnDate: return "Renews on {{ date }}"
        case .purchasesNotFound: return "No past purchases"
        case .purchasesNotRecovered: return "We could not find any purchases with your account. If you think this is an error, please contact support."
        case .purchasesRecovered: return "Purchases restored"
        case .purchasesRecoveredExplanation: return "We restored your past purchases and applied them to your account."
        case .purchasesRestoring: return "Restoring..."
        case .refundCanceled: return "Refund canceled"
        case .refundErrorGeneric: return "An error occurred while processing the refund request. Please try again."
        case .refundGranted: return "Refund requested"
        case .refundStatus: return "Refund status"
        case .refundedAt: return "Refunded At"
        case .renewsOnDate: return "Renews on {{ date }}"
        case .renewsOnDateForPrice: return "Renews on {{ date }} for {{ price}}."
        case .restorePurchases: return "Restore purchases"
        case .sandbox: return "Sandbox"
        case .screenManagementSeeAllPurchases: return "See all purchases"
        case .screenManagementTitle: return "How can we help?"
        case .screenNoActiveSubtitle: return "We can check for previous purchases"
        case .screenNoActiveTitle: return "No subscriptions found"
        case .screenPurchaseHistoryAccountDetailsTitle: return "Account Details"
        case .screenPurchaseHistoryActiveSubscriptionsTitle: return "Active Subscriptions"
        case .screenPurchaseHistoryExpiredSubscriptionsTitle: return "Expired Subscriptions"
        case .screenPurchaseHistoryOriginalPurchaseDate: return "Original Download Date"
        case .screenPurchaseHistoryOthersTitle: return "Others"
        case .screenPurchaseHistoryTitle: return "Purchase History"
        case .screenPurchaseHistoryUserId: return "User ID"
        case .sharedThroughFamilyMember: return "Shared through family member"
        case .singlePaymentThenPrice: return "{{ sub_offer_duration }} for {{ sub_offer_price }}, then {{ price }}"
        case .status: return "Status"
        case .store: return "Store"
        case .stripe: return "Stripe"
        case .subEarliestExpiration: return "This is your subscription with the earliest expiration date."
        case .subEarliestRenewal: return "This is your subscription with the earliest billing date."
        case .subExpired: return "This subscription has expired."
        case .surveyMistake: return "Bought by mistake"
        case .surveyTooExpensive: return "Too expensive"
        case .surveyUsage: return "Don't use the app"
        case .transactionId: return "TransactionID"
        case .trialPeriod: return "Trial Period"
        case .tryCheckRestore: return "We can try checking your Apple account for any previous purchases"
        case .unknown: return "Unknown"
        case .unknownStore: return "Unknown"
        case .unsubscribedAt: return "Unsubscribed At"
        case .updateWarningDescription: return "Downloading the latest version of the app may help solve the problem."
        case .updateWarningIgnore: return "Continue"
        case .updateWarningTitle: return "Update available"
        case .updateWarningUpdate: return "Update"
        case .webStore: return "Web"
        case .webSubscriptionManage: return "You have an active subscription that was purchased on the web. You can manage your subscription using the button below."
        case .yes: return "Yes"
        case .youHaveLifetime: return "Your active lifetime subscription"
        case .youHavePromo: return "You’ve been granted a subscription that doesn’t renew"
        case .youMayHaveDuplicatedSubscriptionsSubtitle: return "You might be subscribed both on the web and through the App Store. To avoid being charged twice, please cancel your iOS subscription in your device settings."
        case .youMayHaveDuplicatedSubscriptionsTitle: return "You may have duplicated subscriptions"
        default: return self.rawValue.capitalized
        }
      }

    }

  }

}
