# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftExample' do

  # Pods for SwiftExample
  pod 'Purchases', :path => '../../'

end

target 'WatchExample Extension' do

  # Pods for SwiftExample
  pod 'Purchases', :path => '../../'
  pod 'TPInAppReceipt', :path => `/Users/andresboedo/Downloads/TPInAppReceipt-master/`
end
