//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//
@import PurchasesCoreSwift;
#include <Purchases/NSData+RCExtensions.h>
#include <Purchases/NSDate+RCExtensions.h>
#include <Purchases/NSDictionary+RCExtensions.h>
#include <Purchases/NSError+RCExtensions.h>
#include <Purchases/RCAttributionData.h>
#include <Purchases/RCAttributionFetcher.h>
#include <Purchases/RCAttributionTypeFactory+Protected.h>
#include <Purchases/RCAttributionTypeFactory.h>
#include <Purchases/RCBackend.h>
#include <Purchases/RCDeviceCache+Protected.h>
#include <Purchases/RCDeviceCache.h>
#include <Purchases/RCEntitlementInfo.h>
#include <Purchases/RCEntitlementInfos.h>
#include <Purchases/RCHTTPClient.h>
#include <Purchases/RCIdentityManager+Protected.h>
#include <Purchases/RCIdentityManager.h>
#include <Purchases/RCInMemoryCachedObject+Protected.h>
#include <Purchases/RCIntroEligibility+Protected.h>
#include <Purchases/RCISOPeriodFormatter.h>
#include <Purchases/RCOffering+Protected.h>
#include <Purchases/RCOffering.h>
#include <Purchases/RCOfferings+Protected.h>
#include <Purchases/RCOfferingsFactory.h>
#include <Purchases/RCProductInfo.h>
#include <Purchases/RCProductInfoExtractor.h>
#include <Purchases/RCPromotionalOffer+Protected.h>
#include <Purchases/RCPurchaserInfo+Protected.h>
#include <Purchases/RCPurchaserInfo.h>
#include <Purchases/RCPurchaserInfoManager+Protected.h>
#include <Purchases/RCPurchaserInfoManager.h>
#include <Purchases/RCPurchases+Protected.h>
#include <Purchases/RCPurchases+SubscriberAttributes.h>
#include <Purchases/RCPurchases.h>
#include <Purchases/RCPurchasesErrorUtils+Protected.h>
#include <Purchases/RCPurchasesErrorUtils.h>
#include <Purchases/RCReceiptFetcher.h>
#include <Purchases/RCSpecialSubscriberAttributes.h>
#include <Purchases/RCStoreKitRequestFetcher.h>
#include <Purchases/RCStoreKitWrapper.h>
#include <Purchases/RCSubscriberAttribute+Protected.h>
#include <Purchases/RCSubscriberAttribute.h>
#include <Purchases/RCSubscriberAttributesManager.h>
#include <Purchases/RCSystemInfo.h>

#include "RCObjC.h"
