# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LegacySwiftExample' do

  # Pods for SwiftExample
  pod 'RevenueCat', :path => '../../'

end

target 'WatchExample Extension' do

  # Pods for SwiftExample
  pod 'RevenueCat', :path => '../../'

end
