# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PurchaseTester' do

  # Pods for SwiftExample
  pod 'Purchases', :path => '../../'
  pod 'PurchasesCoreSwift', :path => '../../'

end

target 'WatchPurchaseTester Extension' do

  # Pods for SwiftExample
  pod 'Purchases', :path => '../../'
  pod 'PurchasesCoreSwift', :path => '../../'

end
