# config.yaml

executionOrder:
  continueOnFailure: false
  flowsOrder:
    - Manage Subscriptions Empty
    - Manage Subscriptions Restore Purchases

flows:
  - customer_center/manage_subscriptions/*
  - customer_center/change_plans/*
  - customer_center/promo_offer/*
