/// This file was autogenerated.
/// DO NOT EDIT THIS FILE.

struct Appearance: Codable {
    let dark: Theme
    let light: Theme
}

struct Theme: Codable {
    let accent_color: String?
    let background_color: String?
    let button_background_color: String?
    let button_text_color: String?
    let text_color: String?
}
