import("../../../fastlane/Fastfile")

desc "Update swift package commit"
lane :update_swift_package_commit do
  backup_extension = '.bck'

  commit_hash = last_git_commit[:commit_hash]
  old_kind_line = "kind = branch;"
  new_kind_line = "kind = revision;"

  sed_regex = 's|' + old_kind_line + '|' + new_kind_line + '|'
  sh("sed", '-i', backup_extension, sed_regex, '../SPMIntegration.xcodeproj/project.pbxproj')

  old_branch_line = "branch = develop;"
  new_revision_line = "revision = #{commit_hash};"

  sed_regex = 's|' + old_branch_line + '|' + new_revision_line + '|'
  sh("sed", '-i', backup_extension, sed_regex, '../SPMIntegration.xcodeproj/project.pbxproj')
end
