# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PurchaseTests' do

  # Pods for SwiftExample
  pod 'Purchases', :path => '../../'
  pod 'PurchasesCoreSwift', :path => '../../'

end

target 'WatchPurchaseTests Extension' do

  # Pods for SwiftExample
  pod 'Purchases', :path => '../../'
  pod 'PurchasesCoreSwift', :path => '../../'

end
