name: Approve release hold

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

permissions: {}

jobs:
  approve:
    permissions:
      pull-requests: read
    uses: revenuecat/sdk-github-workflows/.github/workflows/approve-release-hold.yml@c7a3b97c331c9d5bbddaaae3e25697d76fb6b9c7 # v9
    secrets:
      CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
