name: Run Fastlane and Create PR if Changed

on:
  workflow_dispatch:
  push:
    branches:
      - feat/generate-ios-code  # Trigger on pushes to this branch

jobs:
  fetch_run_and_pr:
    runs-on: macos-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download customer center config from private repo
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          curl -sL \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3.raw" \
            https://api.github.com/repos/RevenueCat/khepri/contents/services/customer_center/domain/default_stored_customer_center_config.json \
            -o config.json

          {
            echo "CONFIG_JSON<<EOF"
            cat config.json
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane
        run: |
          fastlane run_with_customer_center_config config_json:"$CONFIG_JSON"

      - name: Create branch and commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b auto/update-customer-config || git switch auto/update-customer-config
          git add -A

          if ! git diff --cached --quiet; then
            git commit -m "Update based on customer center config"
          else
            echo "No changes to commit."
            echo "no_changes=true" >> "$GITHUB_ENV"
          fi

      - name: Push changes (if any)
        if: env.no_changes != 'true'
        run: |
          git push --set-upstream origin auto/update-customer-config

      - name: Create Pull Request (if changes exist)
        if: env.no_changes != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --head auto/update-customer-config \
            --base main \
            --title "Update from customer center config" \
            --body "This PR was automatically created after processing \`default_stored_customer_center_config.json\`."