name: Issue Notifications

on:
  workflow_dispatch: # Manual trigger for testing
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 * * * *" # Every hour

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Notification Action
        uses: joshdholtz/github-action-issue-ack@v10
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

          # Keywords to raise alert
          title_keywords: "urgent,security,bug,crash"

          # Excluded labels to silence notifications
          excluded_labels: "acknowledged"

          # Reaction and comment thresholds to raise alert
          reaction_threshold: "5"
          comment_threshold: "5"

          # Batch checking configuration
          check_all_open_issues: "true"
          max_issues_to_check: "100"
          issue_state: "open"

          # Custom message for testing
          message_template: |
            **{title}**
            Reactions: {reactions} | Comments: {comments}
            {url}

          # Enable both notification types
          notify_on_create: "true"
          notify_on_threshold: "true"
