name: Issue Notifications

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 * * * *"

jobs:
  notify:
    uses: revenuecat/sdk-github-workflows/.github/workflows/issue-notifications.yml@v2
    secrets:
      ACK_SLACK_WEBHOOK_URL: ${{ secrets.ACK_SLACK_WEBHOOK_URL }}
      ACK_ALERT_KEYWORDS: ${{ secrets.ACK_ALERT_KEYWORDS }}
      ACK_REACTION_THRESHOLD: ${{ secrets.ACK_REACTION_THRESHOLD }}
      ACK_COMMENT_THRESHOLD: ${{ secrets.ACK_COMMENT_THRESHOLD }}
